server:
  port: 8888
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        nanhuiMqSpringStreamProducer:
          destination: NANHUI_MQ_SPRING_STREAM_BEGIN
          exchangeType: topic
          routing-key-expression: '''addProduct.*'''  # 需要用这个来指定 RoutingKey
        example-topic-output:
          destination: delay-topic
        distribute-topic-output:
          destination: distribute-topic
        handler-exception1-topic-output:
          destination: handler-exception1-topic
      rabbit:
        bindings:
          example-topic-output:
            producer:
               delayed-exchange: true
