server:
  port: 9999
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        nanhuiMqSpringStreamConsumer:
          bindingRoutingKey: addProduct.*  # 用来绑定消费者的 routing key
          destination: NANHUI_MQ_SPRING_STREAM_BEGIN
          group: PAAS_MYSQL_PROVIDER   #用于持久化分组
        example-topic-input:
          destination: delay-topic
          group: test

      rabbit:
        bindings:
          example-topic-input:
            consumer:
              delayed-exchange: true
