batman:
  swagger:
    title: api manage RESTful Content APIs
    description: <font color="red">接口文档</font>
    version: 1.0
    modules:
    - {
      model-name: service-feign,
      packages: ["fast.cloud.nacos.controller"],
      group-name: service-feign
    }