mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: fast.cloud.nacos.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8
    username: root
    password: root

logging:
  level:
     fast.cloud.nacos.mybatis.mapper: debug

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: ture
  params: count=countSql
