management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 18085
#spring:
#  application:
#    name: service-gateway
#  cloud:
#        gateway:
#          routes:
#    #        -   filters:
#    #              - StripPrefix=1
#             id: nacos-route
#             predicates:
#                  -   args[pattern]: /service-feign/**
#                      name: Path
#                uri: lb://service-feign
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: service-hi
          uri: lb://service-hi
          predicates:
            - Path=/service-hi/**
          filters:
            - StripPrefix=1
        - id: service-file
          uri: lb://service-file
          predicates:
            - Path=/service-file/**
          filters:
            - StripPrefix=1
#        - id: service-feign
#          uri: lb://service-feign
#          predicates:
#            - Path=/service-feign/**
#          filters:
#            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848