management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 18085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: service-hi
          uri: lb://service-hi
          predicates:
            - Path=/service-hi/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848