server:
  port: 8888

batman:
  swagger:
    title: security provider RESTful APIs
    description: <font color="red">接口文档</font>
    version: 1.0
    modules:
    - {
      model-name: model_one, #模块名称
      packages: ["com.batman.nacos.securityprovider.controller"], #扫描的包路径
      group-name: model_one  #分组名称
    }