# service instance name
spring:
  application:
    name: security-consumer
  # nacos discovery config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 9100

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000