server:
  port: 28080
spring:
  main:
     allow-bean-definition-overriding: true
  application:
    name: service-gateway-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8717
      datasource:
        ds:
          nacos:
            server-addr: localhost:8848
            dataId: service-gateway-sentinel-nacos
            groupId: DEFAULT_GROUP
            rule-type: gw-flow
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
      - id: consumer_server
        uri: lb://service-consumer-fallback-sentinel
        predicates:
          - Path=/service-consumer-fallback-sentinel/**
        filters:
          - StripPrefix=1