version: '3'
services:
    mongodb:
        image: mongo:4.0.5
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime
        ports:
            - 27018:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin